-- SDKWork github consolidated initialization baseline (sqlite)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/sqlite/0001_github_baseline.sql
-- SDKWork github consolidated initialization baseline (sqlite)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/sqlite/0001_github_legacy_baseline.sql
-- github integration baseline schema

CREATE TABLE IF NOT EXISTS github_repository (
    id TEXT PRIMARY KEY NOT NULL,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL,
    full_name TEXT NOT NULL,
    owner TEXT NOT NULL,
    description TEXT,
    default_branch TEXT,
    html_url TEXT,
    is_private INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS github_issue (
    id TEXT PRIMARY KEY NOT NULL,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL,
    repository_id TEXT NOT NULL,
    number INTEGER NOT NULL,
    title TEXT NOT NULL,
    state TEXT NOT NULL,
    html_url TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS github_plan (
    id TEXT PRIMARY KEY NOT NULL,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL,
    repository_id TEXT,
    title TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS github_plan_item (
    id TEXT PRIMARY KEY NOT NULL,
    plan_id TEXT NOT NULL,
    title TEXT NOT NULL,
    status TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    issue_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- folded migration: migrations/sqlite/0002_github_provider_account.sql
-- github provider account linking for tenant-scoped integration credentials

CREATE TABLE IF NOT EXISTS github_provider_account (
    id TEXT PRIMARY KEY NOT NULL,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL,
    provider TEXT NOT NULL DEFAULT 'github',
    external_account_id TEXT,
    access_token_cipher TEXT NOT NULL,
    scopes TEXT,
    status TEXT NOT NULL,
    last_synced_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (tenant_id, organization_id, provider)
);

CREATE INDEX IF NOT EXISTS idx_github_provider_account_scope
    ON github_provider_account (tenant_id, organization_id, provider, status);

-- folded migration: migrations/sqlite/0003_github_oauth_pending.sql
-- ephemeral OAuth state for GitHub integration linking

CREATE TABLE IF NOT EXISTS github_oauth_pending (
    state TEXT PRIMARY KEY NOT NULL,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_github_oauth_pending_expires
    ON github_oauth_pending (expires_at);

-- folded migration: migrations/sqlite/0004_github_referential_integrity.sql
-- Referential integrity indexes and SQLite relationship enforcement.

CREATE INDEX IF NOT EXISTS idx_github_issue_repository
    ON github_issue (repository_id);

CREATE INDEX IF NOT EXISTS idx_github_issue_scope
    ON github_issue (tenant_id, organization_id, repository_id);

CREATE INDEX IF NOT EXISTS idx_github_plan_repository
    ON github_plan (repository_id);

CREATE INDEX IF NOT EXISTS idx_github_plan_scope
    ON github_plan (tenant_id, organization_id, repository_id);

CREATE INDEX IF NOT EXISTS idx_github_plan_item_plan
    ON github_plan_item (plan_id);

CREATE INDEX IF NOT EXISTS idx_github_plan_item_issue
    ON github_plan_item (issue_id);
