use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const GITHUB_HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/repositories",
        "github",
        "repositories.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/repositories/sync",
        "github",
        "repositories.sync",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/issues",
        "github",
        "issues.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/issues/sync",
        "github",
        "issues.sync",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/plans",
        "github",
        "plans.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/github/integration",
        "github",
        "integration.status",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/integration",
        "github",
        "integration.link",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/github/integration",
        "github",
        "integration.unlink",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/github/integration/oauth/begin",
        "github",
        "integration.oauth.begin",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/app/v3/api/github/integration/oauth/callback",
        "github",
        "integration.oauth.callback",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/github/integrations",
        "github",
        "integrations.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/github/integrations/sync",
        "github",
        "integrations.repositories.sync",
    ),
];

pub fn github_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(GITHUB_HTTP_ROUTES)
}

pub fn github_public_path_prefixes() -> Vec<String> {
    vec![
        "/health".to_string(),
        "/healthz".to_string(),
        "/readyz".to_string(),
        "/metrics".to_string(),
    ]
}
